---
- hosts: centos
  user: root

  vars_files:
    - vars/main.yml

  roles:
    - essentials
    - hostname
    - timezone
    - user
    - fail2ban
    - firewall
    - zsh
    - newrelic
    - ssh
    - ufw
    - sysctl

